global:
  scrape_interval: 5s # Server 抓取頻率
  # external_labels:
  #   monitor: "my-monitor"
scrape_configs:
  - job_name: "earthquake"
    static_configs:
      - targets: ["backend:8000"]
  # - job_name: "nginx_exporter"
  #   static_configs:
  #     - targets: ["nginx-prometheus-exporter:9113"]