# Generated by Django 5.2 on 2025-04-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Earthquake',
            fields=[
                ('earthquake_no', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('report_content', models.TextField()),
                ('report_image_uri', models.URLField(blank=True, null=True)),
                ('shakemap_image_uri', models.URLField(blank=True, null=True)),
                ('epicenter', models.CharField(max_length=255)),
                ('epicenter_latitude', models.FloatField()),
                ('epicenter_longitude', models.FloatField()),
                ('magnitude_type', models.CharField(max_length=50)),
                ('magnitude_value', models.FloatField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('taipei', models.CharField(blank=True, max_length=10, null=True)),
                ('taichung', models.CharField(blank=True, max_length=10, null=True)),
                ('tainan', models.CharField(blank=True, max_length=10, null=True)),
                ('taitung', models.CharField(blank=True, max_length=10, null=True)),
            ],
        ),
    ]
