# Generated by Django 5.2 on 2025-04-17 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EarthquakeEvent',
            fields=[
                ('event_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('city', models.CharField(max_length=50)),
                ('area_intensity', models.CharField(max_length=10)),
                ('earthquake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.earthquake')),
            ],
        ),
    ]
