name: CI - Check

on:
  push:
    branches: [develop]
  pull_request:
    branches: [develop]

jobs:
  docker-build:
    name: Build Dockerfile(s)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build backend
        working-directory: ./backend
        run: |
          if [ -f Dockerfile ]; then
            docker build -t backend:test .
          else
            echo "No backend Dockerfile yet"
          fi

      - name: Build frontend
        working-directory: ./frontend
        run: |
          if [ -f Dockerfile ]; then
            docker build -t frontend:test .
          else
            echo "No frontend Dockerfile yet"
          fi

      - name: Build data_ingestion
        working-directory: ./data_ingestion
        run: |
          if [ -f Dockerfile ]; then
            docker build -t data_ingestion:test .
          else
            echo "No data ingestion Dockerfile yet"
          fi

      - name: Run backend tests
        working-directory: ./backend
        run: |
          pip install -r requirements.txt
          PYTHONPATH=. pytest tests

      # - name: Run frontend tests
      #   working-directory: ./frontend
      #   run: npm run test
