name: CD - Deploy to GCP VM via SSH

on:
  push:
    branches: [main]

jobs:
  deploy-to-vm:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.GCE_VM_IP }}
          username: ${{ secrets.GCE_VM_USER }}
          key: ${{ secrets.GCE_SSH_KEY }}
          port: 22
          script: |
            cd /earthquake-event-dispatcher/Earthquake-Event-Dispatcher
            git pull origin main
            docker compose -f docker-compose.yml pull
            docker compose -f docker-compose.yml --env-file .env.production up -d --build backend frontend prometheus grafana