name: CD - Deploy to GCP Cloud Run

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Set up Google Cloud
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_CREDENTIALS }}
          export_default_credentials: true

      - name: Configure Docker for GCP
        run: gcloud auth configure-docker

      - name: Build and push Docker image
        run: |
          docker build -t gcr.io/${{ secrets.GCP_PROJECT_ID }}/earthquake-backend ./backend
          docker push gcr.io/${{ secrets.GCP_PROJECT_ID }}/earthquake-backend

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy earthquake-backend \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/earthquake-backend \
            --region ${{ secrets.GCP_REGION }} \
            --platform managed \
            --allow-unauthenticated